# Generated by Django 3.1.4 on 2024-03-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='last_stock',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上次存貨日期'),
        ),
    ]
