# Generated by Django 3.1.4 on 2024-04-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sum',
            field=models.IntegerField(default=0, verbose_name='總價格'),
        ),
    ]
