# Generated by Django 3.1.4 on 2024-04-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_orderitem_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.IntegerField(default=0, verbose_name='訂單總價格'),
        ),
    ]
