# Generated by Django 3.1.4 on 2024-04-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_auto_20240327_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='圖片'),
        ),
    ]
