# Generated by Django 3.1.4 on 2024-04-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='amont',
            new_name='amount',
        ),
    ]
