# Generated by Django 3.1.4 on 2024-04-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_auto_20240401_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='未實現訂單'),
        ),
    ]
