# Generated by Django 3.1.4 on 2024-04-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_product_ordering'),
        ('POS', '0002_auto_20240320_1355'),
    ]

    operations = [
    ]
