# Generated by Django 3.1.4 on 2024-04-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0007_merge_20240403_1328'),
        ('POS', '0003_order_sum'),
    ]

    operations = [
    ]
